name: Release

on: [repository_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK 11
      uses: joschi/setup-jdk@v1
      with:
        java-version: openjdk11
        architecture: x64
    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v4
      with:
        servers: '[{ "id": "github", "privateKey": "${{ secrets.GITHUB_TOKEN }}" }]'
    - name: Maven stats
      run: mvn -version
    - name: Build with Maven
      run: mvn -B org.codehaus.mojo:build-helper-maven-plugin:3.1.0:parse-version release:prepare release:perform -Darguments="-DexcludedGroups=ui" -DdevelopmentVersion=${parsedVersion.majorVersion}.${parsedVersion.nextMinorVersion}.0-SNAPSHOT
